---
hosts:
  - name: daneel
    ip: 192.168.0.214

provisioners:
  - name: daneel
    host: daneel
    cache:
      type: redis
      parameters:
        host: daneel
        port: 6479
        db: 0

services:
  - service_name: qwen1.5-vllm
    type: vllm-openai-compat
    description: DeepSeek Qwen 1.5B
    parameters:
      model_name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
    varieties:
      amdgpu:
        gpu: True
        image: 'openai-api-vllm.amdgpu'
      nvidia:
        gpu: True
        image: 'openai-api-vllm.nvidia'
      cpuonly:
        gpu: False
        image: 'openai-api-vllm.cpu-only'
    profiles:
      embed:
        parameters:
          cpu_offload_gb: None
          gpu_memory_utilization: 0.7
          max_model_len: 1100
      fast-gpu:
        parameters:
          cpu_offload_gb: None
          gpu_memory_utilization: 0.9
      max-context-window:
        parameters:
          max_model_len: None
      small-context-window:
        parameters:
          max_model_len: 15000
