---
hosts:
  - name: daneel
    ip: 192.168.0.214

provisioners:
  - name: daneel
    host: daneel
    cache:
      type: redis
      parameters:
        host: daneel
        port: 6479
        db: 0

services:
  - name: qwen1.5-vllm
    type: container
    description: DeepSeek Qwen 1.5B
    varieties:
      nvidia:
        image: 'openai-api-vllm.nvidia'
        environment:
          GPU: true
      amdgpu:
        image: 'openai-api-vllm.amdgpu'
        environment:
          GPU: true
      cpu-only:
        image: 'openai-api-vllm.cpu-only'
        environment:
          GPU: false
    profiles:
      embed:
        environment:
          CPU_OFFLOAD_GB: ""
          GPU_MEMORY_UTILIZATION: 0.7
          MAX_MODEL_LEN: 1100
      no-gpu:
        environment:
          MAX_MODEL_LEN: 45000
      fast-gpu:
        environment:
          CPU_OFFLOAD_GB: ""
          GPU_MEMORY_UTILIZATION: 0.9
      max-context-window:
        environment:
          MAX_MODEL_LEN: ""
      small-context-window:
        environment:
          MAX_MODEL_LEN: 15000
